In [1]:
# NumPy is a library for numerical computing in Python. 
# It is used for working with arrays, matrices, and performing mathematical operations on large datasets efficiently.
# NumPy Arrays can be created using array(), zeros(), ones(), arange(), linspace(), and random functions like random.rand(),etc.

# Questions on NumPy

In [2]:
import numpy as np

In [3]:
# 1.  Create a 1D NumPy array of integers from 10 to 50.

a = np.arange(10,51)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [4]:
# 2.  Create a 5x5 matrix with values from 0 to 24.

a1 = np.arange(0,25).reshape(5,5)
a1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [5]:
# 3.  Generate a NumPy array of 10 random numbers between 0 and 1.

a = np.random.rand(10)
a

array([0.47900618, 0.19777037, 0.90181503, 0.3389238 , 0.51237993,
       0.00694453, 0.31544144, 0.98788479, 0.90912784, 0.25367981])

In [6]:
# 4.  Reshape a 1D array of 12 elements into a 4x3 array.

b = np.arange(12).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [7]:
# 5.  Find the sum, mean, and standard deviation of the elements of an array.

arr = np.array([12, 20, 34, 14, 50])
s = np.sum(arr)
m = np.mean(arr)
std = np.std(arr)
s,m,std

(130, 26.0, 14.25482374496437)

In [8]:
# 6.  Multiply two 3x3 matrices.

m1 = np.array([[5, 2, 3], 
                [4, 9, 6], 
                [7, 8, 1]])

m2 = np.array([[2, 8, 7], 
                [8, 5, 4], 
                [3, 6, 9]])

a = np.dot(m1, m2)
a

array([[ 35,  68,  70],
       [ 98, 113, 118],
       [ 81, 102,  90]])

In [9]:
# 7.  Reverse the rows of a 2D NumPy array.

a = np.array([[4, 2, 5], 
            [3, 8, 6], 
            [7, 1, 9]])

rev = a[::-1]
rev

array([[7, 1, 9],
       [3, 8, 6],
       [4, 2, 5]])

In [10]:
# 8.  Get the maximum and minimum values from an array.

a = np.array([15, 42, 7, 89, 34, 22])
mx = np.max(a)
mn = np.min(a)
mx,mn

(89, 7)

In [11]:
# 9.  Extract the diagonal elements of a square matrix.

m = np.array([[11, 23, 37], 
                [41, 59, 63], 
                [76, 81, 90]])
n = np.diagonal(m)
n

array([11, 59, 90])

In [12]:
# 10. Create an identity matrix of size 5x5.

l = np.identity(5)
l

# Note: we can also use eye() function to do the same.

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
# 11. Find the cumulative sum of an array of 10 random integers.

rint = np.random.randint(12,45,10)
cs = np.cumsum(rint)
rint,cs

(array([17, 32, 34, 26, 40, 39, 23, 21, 41, 14]),
 array([ 17,  49,  83, 109, 149, 188, 211, 232, 273, 287]))

In [14]:
# 12. Perform element-wise multiplication of two arrays.

a1 = np.array([12, 42, 36, 38, 5])
a2 = np.array([10, 25, 32, 47, 55])
r = a1 * a2
r

array([ 120, 1050, 1152, 1786,  275])

In [15]:
# 13. Flatten a 3x3 matrix into a 1D array.

b = np.array([[34, 12, 53], 
                [46, 5, 16], 
                [73, 85, 9]])

f = b.flatten()
f

# Note: we can also use ravel() function to do the same.

array([34, 12, 53, 46,  5, 16, 73, 85,  9])

In [16]:
# 14. Generate an array of evenly spaced numbers between 5 and 20 (with 10 steps).

d = np.linspace(5, 20, 10)
d

# Note: linspace() function creates an array of evenly spaced values over a specified range, including both start and endpoints.

array([ 5.        ,  6.66666667,  8.33333333, 10.        , 11.66666667,
       13.33333333, 15.        , 16.66666667, 18.33333333, 20.        ])

In [17]:
# 15. Compute the eigenvalues of a 3x3 matrix.

m = np.array([[42, 2, 19], 
            [21, 35, 10], 
            [18, 13, 2]])
eigenvals = np.linalg.eigvals(m)
eigenvals

array([56.54740532, 28.12794589, -5.67535121])

In [18]:
# 16. Compute the eigenvectors of a 3x3 matrix.

m = np.array([[5, 14, 9], 
            [21, 5, 10], 
            [12, 9, 21]])
_, eigenvecs = np.linalg.eig(m)
eigenvecs

array([[-0.4551503 , -0.63905138, -0.4130139 ],
       [-0.54233108,  0.76883224, -0.54383422],
       [-0.70619771,  0.02259037,  0.73052301]])

In [19]:
# 17. Replace all odd numbers in a NumPy array with -1.

a = np.array([10, 15, 22, 13, 42, 55])
a[a % 2 != 0] = -1
a

array([10, -1, 22, -1, 42, -1])

In [20]:
# 18. Find indices of elements in a NumPy array that are greater than a given value.

c = np.array([5, 12, 18, 7, 22, 30, 4])
val = 13
n = np.where(c > val)
n

(array([2, 4, 5], dtype=int64),)

In [21]:
# 19. Create a 3D NumPy array and access its second layer.

arr = np.array([[[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]],

                [[10, 11, 12], 
                [13, 14, 15], 
                [16, 17, 18]],

                [[19, 20, 21], 
                [22, 23, 24], 
                [25, 26, 27]]])

s = arr[1]
s

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [22]:
# 20. Concatenate 2D array horizontally and vertically.

g=np.array([[45,65,23],[23,45,67],[11,33,55]])
h=np.array([[12,45,76],[32,54,65],[98,34,16]])

print(np.vstack((g,h)))
print(np.hstack((g,h)))

[[45 65 23]
 [23 45 67]
 [11 33 55]
 [12 45 76]
 [32 54 65]
 [98 34 16]]
[[45 65 23 12 45 76]
 [23 45 67 32 54 65]
 [11 33 55 98 34 16]]
